import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/UI/Footer";

const geistMonoBold = localFont({
  src: "./fonts/Geist-Bold.otf",
  variable: "--font-geist-bold",
  weight: "100 900",
});
const geistMonoMedium = localFont({
  src: "./fonts/Geist-Medium.otf",
  variable: "--font-geist-medium",
  weight: "100 900",
});
const geistMonoRegular = localFont({
  src: "./fonts/Geist-Regular.otf",
  variable: "--font-geist-regular",
  weight: "100 900",
});
const geistMonoSemiBold = localFont({
  src: "./fonts/Geist-SemiBold.otf",
  variable: "--font-geist-semibold",
  weight: "100 900",
});

export const metadata = {
  title: "Starlite",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistMonoBold.variable} ${geistMonoMedium.variable} ${geistMonoRegular.variable} ${geistMonoSemiBold.variable}   antialiased`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
